### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'Kevo'.

### ISSUE THREAD

**Issue by RXM307** [gaggle331/home-assistant-kevo#10]
Appear Home Assistant now requires a version, currently I'm on HA 2021.3.4

No 'version' key in the manifest file for custom integration 'kevo_plus'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'kevo_plus'

hopefully should just require a simple version key in the manifest file, I'll submit a Pull request once I confirm.

**Comment by RXM307** [comment]
pull request created https://github.com/gaggle331/home-assistant-kevo/pull/11

**Comment by gaggle331** [comment]
Merged!
