### ISSUE TITLE
This no longer works with reCaptcha implemented on Kevo login page

### ISSUE THREAD

**Issue by steve28** [gaggle331/home-assistant-kevo#4]
Is it working for you?

**Comment by devinslick** [comment]
> Is it working for you?

I think this is unlikely to get a reliable fix.
Before I replace my Kevo devices, I'm going to be sure to let Kevo know what I think about this.
Their captcha seems designed to prevent programmatic access.  If it was done for security reasons they'd have enabled multi-factor authentication.
