### ISSUE TITLE
Issue in 0.111.1 LockDevice is deprecated

### ISSUE THREAD

**Issue by RXM307** [gaggle331/home-assistant-kevo#6]
2020-06-13 21:37:28 WARNING (MainThread) [homeassistant.components.lock] LockDevice is deprecated, modify KevoDevice to extend LockEntity

My be present in older versions but only got around to installing this....

If I get a chance I'll try to work out what changes are needed but python is not my strength.

**Comment by aLTeReGo-SWI** [comment]
Seeing the same thing in 0.114.1

LockDevice is deprecated, modify KevoDevice to extend LockEntity

**Comment by RXM307** [comment]
these commits in this pull request "should" fix this issue but I personally haven't tested this yet

https://github.com/gaggle331/home-assistant-kevo/pull/8

**Comment by gaggle331** [comment]
I merged that pull request, hopefully the issue is fixed. I don't lose my Kevo locks anymore so I can't test, but I'll try to keep up with merge requests as best I can.

**Comment by RXM307** [comment]
Thanks this works.
